
// .js file is generated by npm script "compile-to-media" :
// - do not modify .js file
// - execute npm script "compile-to-media" before F5
// 
// This code is shared with media directory
// The instances are NOT shared
// All methods/attributs called media... should be used only by media/*.js, methods cannot access the main VS Code APIs directly 
// All methods/attributs called src...   should be used only by src/*.ts,   methods cannot access html objects

import type { ExtensionContext } from "vscode";

type Message = { [key: string]: any };

let mediaSendMessage: ((message: Message) => void) | null = null;

class Checkbox {
	public  readonly id: string;                             // id inside message and load/save into context
	private readonly checkboxId: string;                     // id inside html
	private readonly checkboxLabelId: string;                // id inside html
    public           srcHtmlClasses: string = "";
    public           label: string;  // label of html checkbox
    // if null, no save/load, should be a main checkbox, recomputed by main.js
	private readonly srcDefaultValue: boolean | null;
	public           srcValue: boolean | null;
    public  readonly media: {
        htmlCheckbox: HTMLInputElement,       // element <checkboxId> from document
        htmlCheckboxLabel: HTMLLabelElement,  // element <checkboxLabelId> from document
    } | null = null;

    constructor(id: string, mediaDocument: Document | null, label: string, defaultValue: boolean | null) {
        this.id = id;
        this.checkboxId = `${this.id}-checkbox`;
        this.checkboxLabelId = `${this.id}-label`;
        this.label = label;
        this.srcDefaultValue = defaultValue;
        this.srcValue = defaultValue;

        if (mediaDocument) {
            this.media = {
                htmlCheckbox: mediaDocument.getElementById(this.checkboxId) as HTMLInputElement,
                htmlCheckboxLabel: mediaDocument.getElementById(this.checkboxLabelId) as HTMLLabelElement,
            };
            this.label = this.media.htmlCheckboxLabel.textContent!;
        }
    }
    mediaAddEventListener(method: any) {
        this.media!.htmlCheckbox.addEventListener('input', (event: any) => { method(event); });
    }
    mediaUpdateMessage(message: Message) {
        message[this.id] = this.media!.htmlCheckbox.checked;
        message[this.checkboxLabelId] = this.label;
        console.log(this.id, `mediaUpdateMessage message[${this.id}]`, message[this.id], `message[${this.checkboxLabelId}]`, message[this.checkboxLabelId]);
    }

    srcInit(context: ExtensionContext) {
        if (this.srcDefaultValue === null) {
            console.log("srcInit this.srcDefaultValue === null, so srcValue no initialized");
            return;
        }
        this.srcValue = context.workspaceState.get<boolean>(this.id, this.srcDefaultValue);
        // label can be not saved when hard-coded
        this.label = context.workspaceState.get<string>(this.checkboxLabelId, this.label);
    }
    srcSaveStatus(context: ExtensionContext) {
        if (this.srcValue === null) {
            console.log("srcSaveStatus this.srcValue === null");
            return;
        }
        context.workspaceState.update(this.id, this.srcValue);
        context.workspaceState.update(this.checkboxLabelId, this.label);
    }
    srcFromMessage(message: Message) {
        if (!(this.id in message)) {
            console.log(`srcFromMessage ${this.id} not in message`);
            return;
        }
        this.srcValue = message[this.id];
        this.label = message[this.checkboxLabelId];
    }
    srcGetHtmls(): string[] {
        const classDecl = this.srcHtmlClasses !== '' ? `class="${this.srcHtmlClasses}"` : '';
        const state = this.srcValue ? "checked" : "";
        const html = `<input type="checkbox" ${state} id="${this.checkboxId}" ${classDecl} /> <label for="${this.checkboxId}" id="${this.checkboxLabelId}">${this.label}</label>`;
        return [html];
    }
}

export class EditAdapter {
	public  readonly id: string;
	private readonly removeEltId: string;
    private readonly media: {
        removeButton: HTMLButtonElement;
    } | null = null;

    constructor(id: string, mediaDocument: Document | null) {
        this.id = id;
        this.removeEltId = `${this.id}-removeElt`;

        if (mediaDocument) {
            this.media = {
                removeButton: mediaDocument.getElementById(this.removeEltId) as HTMLButtonElement,
            };
        }
    }

    mediaAddEventListener(method: any) {
        this.media!.removeButton.addEventListener('click', () => {
            console.log("mediaRemoveButton input");
            method(this);
        });
    }

    srcGetHtmls(): string[] {
        return [`<button id="${this.removeEltId}">&#10134;</button>`];
    }
}

class CheckboxManager {
    public  readonly id: string;
    public  readonly addEltId: string;
	private readonly mainElt: Checkbox;  // All checkbox permits to select/unselect all elts
	public  readonly elts: Checkbox[];
	private readonly idToEditAdapters: { [key: string]: EditAdapter } | null = null;
    private readonly autonomous: boolean;
    public htmlTable: boolean = false;
    private readonly media: {
        document: Document;
        eventListenerMethod: any;  // null until mediaAddEventListener, still null if autonomous
    } | null = null;


	constructor(id: string, elts: Checkbox[], mainElt: Checkbox, mediaDocument: Document | null = null,
                editable: boolean = false,
                autonomous: boolean = false) {
        this.id = id;
        this.addEltId = `${this.id}-addElt`;
        this.elts = elts;           // can be empty until srcInit
        this.mainElt = mainElt;

        if (mediaDocument) {
            this.media = {
                document: mediaDocument,
                eventListenerMethod: null,
            };
            this.mediaInit_CheckboxManager(this.media.document);
        }

        if (editable) {
            this.idToEditAdapters = {};
            for (const elt of this.elts) {
                this.idToEditAdapters[elt.id] = new EditAdapter(elt.id, mediaDocument);
            }
        }

        this.autonomous = autonomous;
    }
    private mediaInit_CheckboxManager(document: Document) {
        if (this.elts.length === 0) {
            // Elts are builded/added dynamically
            const group = document.getElementById(this.id) as HTMLElement;
            const descendants = group.getElementsByTagName("*");
            for (const idx in descendants) {
                const htmlElt = descendants[idx] as HTMLElement;
                // console.log("mediaInit_CheckboxManager elt in group.getElementsByTagName *", htmlElt);

                if (htmlElt.id && htmlElt.id.endsWith("-elt")) {
                    const eltName = htmlElt.id.slice(0, -4);
                    this.mediaBuildAndAddElt(eltName, document);
                }            
            }
        }

        if (this.mainElt) {
            this.mediaComputeMainCheckbox();
        }
    }
    mediaBuildElt(_eltName: string, _document: Document): Checkbox | null {
        // Must override if needed
        return null;
    }
    mediaBuildAndAddElt(eltName: string, document: Document): Checkbox | null {
        const elt = this.mediaBuildElt(eltName, document);
        if (elt) {
            console.log("mediaBuildAndAddElt add new elt", eltName);
            this.elts.push(elt);
            if (this.idToEditAdapters !== null) {
                this.idToEditAdapters[elt.id] = new EditAdapter(elt.id, document);
            }
        }
        return elt;
    }
    mediaRemoveChild(elt: Checkbox) {
        console.log("mediaRemoveChild", elt);

        // Send remove message
        const message: Message = {
            manager: `${this.id}`,
            command: `remove`,
        };
        message[elt.id] = true;
        console.log("mediaRemoveChild mediaSendMessage", message);
        mediaSendMessage!(message);

        // Remove html
        const eltHtml = document.getElementById( `${elt.id}-elt`)!;
        eltHtml.parentNode!.removeChild(eltHtml);
        
        // Remove elt from this
        const index = this.elts.indexOf(elt, 0);
        console.log("mediaRemoveChild index", index);
        this.elts.splice(index, 1);
    }
    mediaGenerateNewChildId(): string {
        let max = -1;
        for (const elt of this.elts) {
            const subIdStr = elt.id.split('-')[1];
            const subId: number = +subIdStr;
            max = Math.max(max, subId);
        }
        return `${this.id}-${max+1}`;
    }
    mediaAddChildHtml(eltId: string, eltHtmls: string[]) {
        console.log("mediaAddChildHtml", eltId, eltHtmls);

        if (this.idToEditAdapters !== null) {
            eltHtmls.push(... new EditAdapter(eltId, null).srcGetHtmls());
        }

        // Add html into document
        const newRow: HTMLElement = document.createElement(this.htmlTable ? 'tr' : 'div');
        newRow.id = `${eltId}-elt`;  // TODO duplicate id
        newRow.innerHTML = this.srcGetHtmlEltRaw(eltId, eltHtmls);
        const rowBeforeId = `${this.elts ? this.elts.at(-1)!.id : this.mainElt.id}-elt`;
        const rowBefore = document.getElementById(rowBeforeId)!;
        rowBefore.parentNode!.insertBefore(newRow, rowBefore.nextSibling);

        // Build new element (initialized from html)
        const elt = this.mediaBuildAndAddElt(eltId, document)!;

        // Add listener
        this.mediaEltAddEventListener(elt);

        // Send add message
        const message: Message = {
            manager: `${this.id}`,
            command: `add`,
            eltIdToAdd: eltId,
        };
        elt.mediaUpdateMessage(message);
        console.log("mediaAddChildHtml mediaSendMessage", message);
        mediaSendMessage!(message);
    }
    mediaEltAddEventListener(elt: Checkbox) {
        elt.mediaAddEventListener((event: any) => { this.mediaEventListenerInnerMethod(event); });
        if (this.idToEditAdapters) {
            this.idToEditAdapters[elt.id].mediaAddEventListener((_editAdapter: EditAdapter) => {
                delete this.idToEditAdapters![elt.id];
                this.mediaRemoveChild(elt);
            });
        }
    }
    mediaAddEventListener(method: any) {
        this.media!.eventListenerMethod = method;

        for (const elt of this.elts) {
            this.mediaEltAddEventListener(elt);
        }
        if (this.mainElt) {
            this.mainElt.mediaAddEventListener((event: any) => { this.mediaEventListenerInnerMethod(event); });
        }
    }
    private mediaEventListenerInnerMethod(event: any) {
        this.mediaManage(event);

        if (this.media!.eventListenerMethod) {
            console.log("mediaAddEventListenerInner callback call method");
            this.media!.eventListenerMethod(event);
        }
        else {
            console.log("mediaAddEventListenerInner callback call mediaBuildMessage");
            const message = this.mediaBuildMessage();
            console.log("mediaAddEventListenerInner callback call mediaSendMessage");
            mediaSendMessage!(message);
        }
    }
    mediaUpdateMessage(message: Message) {
        if (this.autonomous) {
            console.error("mediaUpdateMessage must not be called if autonomous");
        }

        for (const elt of this.elts) {
            elt.mediaUpdateMessage(message);
        }
    }
    mediaBuildMessage(): {} {
        if (!this.autonomous) {
            console.error("mediaBuildMessage must not be called if not autonomous");
        }

        const message = {
            manager: `${this.id}`,
            command: `exec`,
        };

        for (const elt of this.elts) {
            elt.mediaUpdateMessage(message);
        }
        return message;
    }

    private mediaManage(event: any) {
        if (this.mainElt.media!.htmlCheckbox === event.target) {
            // Change all subCheckboxes
            for (const elt of this.elts) {
                if (elt.media!.htmlCheckbox) {
                    elt.media!.htmlCheckbox.checked = event.target?.checked;
                }
            }
            return;
        }

        for (const elt of this.elts) {
            if (elt.media!.htmlCheckbox === event.target) {
                this.mediaComputeMainCheckbox();
                return;
            }
        }

        // Impossible
    }

    private mediaComputeMainCheckbox() {
        const allChecked = [...this.elts].every(elt => elt.media!.htmlCheckbox.checked);
        if (this.mainElt && this.mainElt.media!.htmlCheckbox) {
            this.mainElt.media!.htmlCheckbox.checked = allChecked;
        }
    }

    srcInit(context: ExtensionContext) {
        const eltNames = context.workspaceState.get<string[]>(`${this.id}Elts`, []);
        console.log(this.id, "srcInit", eltNames, "this.elts.length", this.elts.length);

        if (this.elts.length === 0) {
            // Elts are builded/added dynamically
            for (const eltName of eltNames) {
                this.srcBuildAndAddElt(eltName, context);
            }
        }
        console.log(this.id, "srcInit", "this.elts.length", this.elts.length);

        for (const elt of this.elts) {
            elt.srcInit(context);
        }
        if (this.mainElt) {
            for (const elt of this.elts) {
                elt.srcHtmlClasses = "subCheckbox";
            }
        }
        // mainElt not computed because useless ?
    }
    srcBuildElt(_eltName: string, _context: ExtensionContext): Checkbox | null {
        // Must override if needed
        return null;
    }
    srcBuildAndAddElt(eltName: string, context: ExtensionContext): Checkbox | null {
        const elt = this.srcBuildElt(eltName, context);
        if (elt) {
            console.log(this.id, "srcBuildAndAddElt", eltName);
            this.elts.push(elt);
            if (this.idToEditAdapters !== null) {
                this.idToEditAdapters[elt.id] = new EditAdapter(elt.id, null);
            }
        }
        return elt;
    }
    srcSaveStatus(context: ExtensionContext) {
        const eltNames = [...this.elts].map(elt => elt.id);
        console.log("srcSaveStatus", eltNames);
        context.workspaceState.update(`${this.id}Elts`, eltNames);

        for (const elt of this.elts) {
            elt.srcSaveStatus(context);
        }
        // mainElt not saved
    }
    srcFromMessage(message: Message) {
        for (const elt of this.elts) {
            elt.srcFromMessage(message);
        }
    }
    srcManageManagerMessage(message: Message, context: ExtensionContext) {
        console.log(this.id, `srcManageManagerMessage ${message.command}`, message);
        switch (message.command) {
            case 'exec':
                this.srcFromMessage(message);
                this.srcSaveStatus(context);
                return;

            case 'add':
                const elt = this.srcBuildAndAddElt(message.eltIdToAdd, context)!;
                elt.srcFromMessage(message);
                this.srcSaveStatus(context);
                return;

            case 'remove':
                for (const elt of this.elts) {
                    if (elt.id in message) {
                        // Remove elt from this
                        const index = this.elts.indexOf(elt, 0);
                        console.log("srcManageManagerMessage remove index", index);
                        this.elts.splice(index, 1);

                        this.srcSaveStatus(context);
                        return;
                    }
                }
                console.error(`No elt to remove in`, message);
                return;

            default:
                console.error(this.id, `srcManageManagerMessage ${message.command} ???`, message);
                return;
        }
    }
    srcGetHtml(): string {
        let html = "";
        html += `<div id="${this.id}">`;
        if (this.htmlTable) {
            html += `<table>`;
            html += `<tbody>`;
        }

        if (this.mainElt) {
            html += this.srcGetHtmlElt(`${this.mainElt.id}-mainElt`, this.mainElt.id, this.mainElt.srcGetHtmls());
        }
        for (const elt of this.elts) {
            html += this.srcGetHtmlElt(`${elt.id}-elt`, elt.id, elt.srcGetHtmls());
        }

        const finalRow = this.srcGetHtmlFinalRow();
        if (finalRow) {
            html += this.srcGetHtmlElt(this.addEltId, this.addEltId, finalRow);
        }

        if (this.htmlTable) {
            html += `</tbody>`;
            html += `</table>`;
        }

        html += `</div>`;
        return html;
    }
    private srcGetHtmlElt(eltEltId: string, eltId: string, eltHtmls: string[]): string {
        let html = "";
        if (this.htmlTable) {
            html += `<tr id="${eltEltId}">`;
            html += this.srcGetHtmlEltRaw(eltId, eltHtmls);
            html += `</tr>`;
        }
        else {
            html += `<div id="${eltEltId}">`;
            html += this.srcGetHtmlEltRaw(eltId, eltHtmls);
            html += `</div>`;
        }
        return html;
    }
    private srcGetHtmlEltRaw(eltId: string, eltHtmls: string[]): string {
        if (this.idToEditAdapters !== null && eltId in this.idToEditAdapters) {
            eltHtmls.push(...this.idToEditAdapters[eltId].srcGetHtmls());
        }

        let html = "";
        if (this.htmlTable) {
            for (const eltHtml of eltHtmls) {
                html += `<td>${eltHtml}</td>`;
            }
        }
        else {
            for (const eltHtml of eltHtmls) {
                html += `<div>${eltHtml}</div>`;
            }
        }
        return html;
    }
    srcGetHtmlFinalRow(): string[] {
        // Must override if needed
        return [];
    }
    protected srcGetEltByLabel(label: string): Checkbox | null {
        for (const elt of this.elts) {
            if (elt.label === label) {
                return elt;
            }
        }
        return null;
    }
}

type CaseFunction = (input: string, ) => string;
type ConvertFctSeparator = [CaseFunction | null, string];  // Convert function + their separator

export class CaseCheckbox extends Checkbox {
	public readonly convertFctData: ConvertFctSeparator;

    constructor(id: string, mediaDocument: Document | null, label: string, defaultValue: boolean | null, caseFunction: CaseFunction | null, caseSeparator: string) {
        super(id, mediaDocument, label, defaultValue);
        this.convertFctData = [caseFunction, caseSeparator];
    }
}

export class CaseManager extends CheckboxManager {
	public readonly all       :     Checkbox;
	public readonly kebab     : CaseCheckbox;
	public readonly camel     : CaseCheckbox;
	public readonly pascal    : CaseCheckbox;
	public readonly snake     : CaseCheckbox;
	public readonly upperSnake: CaseCheckbox;
	public readonly capital   : CaseCheckbox;
	public readonly path      : CaseCheckbox;

	constructor(mediaDocument: Document | null = null) {
        // import { paramCase ...} from "change-case" seems not possible in media
        // So can not put here the function
        let all        = new     Checkbox('allCases',       mediaDocument, 'All',              null);
        let kebab      = new CaseCheckbox('kebabCase',      mediaDocument, 'kebabCase',        true, null, "-");
        let camel      = new CaseCheckbox('camelCase',      mediaDocument, 'camelCase',        true, null,  "");
        let pascal     = new CaseCheckbox('pascalCase',     mediaDocument, 'PascalCase',       true, null,  "");
        let snake      = new CaseCheckbox('snakeCase',      mediaDocument, 'snake_case',       true, null, "_");
        let upperSnake = new CaseCheckbox('upperSnakeCase', mediaDocument, 'UPPER_SNAKE_CASE', true, null, "_");
        let capital    = new CaseCheckbox('capitalCase',    mediaDocument, 'Capital Case',     true, null, " ");
        let path       = new CaseCheckbox('pathCase',       mediaDocument, 'path/case',        true, null, "/");

        let elts = [
            kebab,
            camel,
            pascal,
            snake,
            upperSnake,
            capital,
            path,
        ];
        super("case", elts, all, mediaDocument);

        this.all           = all;
        this.kebab         = kebab;
        this.camel         = camel;
        this.pascal        = pascal;
        this.snake         = snake;
        this.upperSnake    = upperSnake;
        this.capital       = capital;
        this.path          = path;

        if (mediaDocument === null) {
            // import { paramCase ...} from "change-case" seems not possible in media
            import("change-case")
            .then((module) => {
                this.kebab.convertFctData[0]      = module.paramCase;
                this.camel.convertFctData[0]      = module.camelCase;
                this.pascal.convertFctData[0]     = module.pascalCase;
                this.snake.convertFctData[0]      = module.snakeCase;
                this.upperSnake.convertFctData[0] = module.constantCase;
                this.capital.convertFctData[0]    = module.capitalCase;
                this.path.convertFctData[0]       = module.pathCase;
            })
            .catch((err) => {
                console.error('import ko', err.message);
            });
        }
    }

    srcGetSelectedCaseFunctions(message: Message): ConvertFctSeparator[] {
        let selectedCaseFunctions: ConvertFctSeparator[] = [];
        for (const elt of this.elts) {
            if (message[elt.id]) {
                selectedCaseFunctions.push((elt as CaseCheckbox).convertFctData);
            }
        }
        return selectedCaseFunctions;
    }
}

export class WordManager extends CheckboxManager {
    private readonly wholeWord: Checkbox;
    private readonly beginWord: Checkbox;
    private readonly endWord:   Checkbox;
    
    constructor(mediaDocument: Document | null = null) {
        let wholeWord = new Checkbox('wholeWord', mediaDocument, 'Whole word', null);
        let beginWord = new Checkbox('beginWord', mediaDocument, 'Begin word', false);
        let endWord   = new Checkbox('endWord',   mediaDocument, 'End word',   false);
    
        let elts = [
            beginWord,
            endWord,
        ];
        super("word", elts, wholeWord, mediaDocument);

        this.wholeWord = wholeWord;
        this.beginWord = beginWord;
        this.endWord   = endWord;

        // this.htmlTable = true;
    }
}

export class CheckboxAdd {
    private readonly manager: FilesToIncludeManager;  // TODO autre type ?
	private readonly id: string;                             // id inside message and load/save into context
    private readonly htmlLabelId : string;
    private readonly htmlApplyId: string;
    private readonly media: {
        label: HTMLInputElement,
        button: HTMLButtonElement;
    } | null = null;

    constructor(manager: FilesToIncludeManager, id: string, mediaDocument: Document | null) {
        this.manager = manager;
        this.id = id;
        this.htmlLabelId  = `${this.id}-label`;
        this.htmlApplyId = `${this.id}-apply`;

        if (mediaDocument) {
            this.media = {
                label:  mediaDocument.getElementById(this.htmlLabelId ) as HTMLInputElement,
                button: mediaDocument.getElementById(this.htmlApplyId)  as HTMLButtonElement,
            };
        }
    }

    mediaAddEventListener() {
        this.media!.button.addEventListener('click', () => {
            console.log("mediaAddEventListener click");

            const id = this.manager.mediaGenerateNewChildId();
            const html = this.manager.mediaGetNewEltHtmls(id, this.media!.label.value, "");
            this.manager.mediaAddChildHtml(id, html);
        });
    }

    srcGetHtmls(): string[] {
        const htmls = [];
        htmls.push(`<input  id="${this.htmlLabelId }" type="text" placeholder="*.cpp,*.c,*.h">`);
        htmls.push(`<button id="${this.htmlApplyId}">&#10133;</button>`);
        return htmls;
    }
}

export class FilesToManager extends CheckboxManager {
    private readonly addElt: CheckboxAdd;

    constructor(id: string, mediaDocument: Document | null = null) {
        let all                  = new Checkbox(`${id}All`,     mediaDocument, "All",     null);

        super(id, [], all, mediaDocument, true, true);
        this.addElt = new CheckboxAdd(this, this.addEltId, mediaDocument);

        this.htmlTable = true;
    }

    mediaGetNewEltHtmls(id: string, label: string, _text: string): string[] {
        console.log(this.id, "mediaGetNewEltHtml", id);
        const elt = new Checkbox(id, null, label, false);
        elt.srcHtmlClasses = "subCheckbox";
        const html = elt.srcGetHtmls();
        console.log(this.id, "mediaGetNewEltHtmls", html);
        return html;
    }
    mediaBuildElt(eltName: string, document: Document): Checkbox | null {
        console.log("mediaBuildElt returns new Checkbox", eltName);
        return new Checkbox(eltName, document, "", false);
    }
    mediaAddEventListener(method: any) {
        super.mediaAddEventListener(method);
        this.addElt.mediaAddEventListener();
    }

    srcBuildElt(eltName: string, _context: ExtensionContext): Checkbox | null {
        console.log("srcBuildElt returns new Checkbox", eltName);
        return new Checkbox(eltName, null, "", false);
    }
    srcGetHtmlFinalRow(): string[] {
        return this.addElt.srcGetHtmls();
    }

    protected srcComputeFilesTo(message: Message): string | null {
        console.log("srcComputeFilesTo", message);
        const filesTo: string[] = [];
        for (const elt of this.elts) {
            if (elt.id in message) {
                if (message[elt.id] === true) {
                    filesTo.push(elt.label);
                }
            }
        }
        const filesToStr = filesTo.join(',');
        console.log("filesToStr", filesToStr);
        return filesToStr;
    }
}

export class FilesToIncludeManager extends FilesToManager {
    constructor(mediaDocument: Document | null = null) {
        super("filesToInclude", mediaDocument);
    }

    srcManageManagerMessage(message: Message, context: ExtensionContext) {
        super.srcManageManagerMessage(message, context);
        switch (message.command) {
            case 'exec':
                import("vscode")
                .then((vscode) => {
                    vscode.commands.executeCommand("workbench.action.findInFiles", {
                        triggerSearch: true,
                        filesToInclude: this.srcComputeFilesTo(message),
                    });
                })
                .catch((err) => {
                    console.error('import ko', err.message);
                });
                return;
        }
    }
}

export class FilesToExcludeManager extends FilesToManager {
    constructor(mediaDocument: Document | null = null) {
        super("filesToExclude", mediaDocument);
    }

    srcManageManagerMessage(message: Message, context: ExtensionContext) {
        super.srcManageManagerMessage(message, context);
        switch (message.command) {
            case 'exec':
                import("vscode")
                .then((vscode) => {
                    vscode.commands.executeCommand("workbench.action.findInFiles", {
                        triggerSearch: true,
                        filesToExclude: this.srcComputeFilesTo(message),
                    });
                })
                .catch((err) => {
                    console.error('import ko', err.message);
                });
                return;
        }
    }
}

// Defines some parts of the mmi
export class Mmi {
    public readonly caseManager: CaseManager;
    public readonly wordManager: WordManager;
    public readonly filesToIncludeManager: FilesToIncludeManager;
    public readonly filesToExcludeManager: FilesToExcludeManager;
    public readonly managers: CheckboxManager[];
    private readonly mainManagers: CheckboxManager[];
    private readonly otherManagers: CheckboxManager[];

	constructor(mediaDocument: Document | null = null, mediaSendMsg = null) {
        this.caseManager           = new CaseManager(mediaDocument);
        this.wordManager           = new WordManager(mediaDocument);
        this.filesToIncludeManager = new FilesToIncludeManager(mediaDocument);
        this.filesToExcludeManager = new FilesToExcludeManager(mediaDocument);
        this.mainManagers  = [this.caseManager, this.wordManager];
        this.otherManagers = [this.filesToIncludeManager, this.filesToExcludeManager];
        this.managers      = this.mainManagers.concat(this.otherManagers);
        mediaSendMessage = mediaSendMsg;
    }

    mediaAddEventListener(method: any) {
        for (const manager of this.mainManagers) {
            manager.mediaAddEventListener(method);
        }
        for (const manager of this.otherManagers) {
            manager.mediaAddEventListener(null);
        }
    }
    mediaUpdateMainMessage(message: Message) {
        for (const manager of this.mainManagers) {
            manager.mediaUpdateMessage(message);
        }
    }

    srcInit(context: ExtensionContext) {
        for (const manager of this.managers) {
            manager.srcInit(context);
        }
    }
    srcFromMainMessage(message: Message, context: ExtensionContext) {
        for (const manager of this.mainManagers) {
            manager.srcFromMessage(message);
            manager.srcSaveStatus(context);
        }
    }
    srcManageManagerMessage(message: Message, context: ExtensionContext) {
        if (!('manager' in message)) {
            console.error("srcManageManagerMessage manager not in", message);
            return;
        }

        const managerId = message.manager;
        for (const manager of this.otherManagers) {
            if (manager.id === managerId) {
                manager.srcManageManagerMessage(message, context);
                manager.srcSaveStatus(context);
                return;
            }
        }

        console.error("srcManageManagerMessage manager", managerId, " not found");
    }
}
