
// .js file is generated by npm script "compile-to-media" :
// - do not modify .js file
// - execute npm script "compile-to-media" before F5

type Message = { [key: string]: any };

let mediaSendMessage: ((message: Message) => void) | null = null;

class MediaCheckbox {
	public  readonly id: string;                             // id inside message and load/save into context
	private readonly checkboxId: string;                     // id inside html
	private readonly checkboxLabelId: string;                // id inside html
	private readonly editEltId: string;
	private readonly removeEltId: string;
    public  readonly editable: boolean;                      // removeable + label is writeable (so saved and loaded)
    public           htmlClasses: string = "";
    public           label: string;            // label of html checkbox
    // if null, no save/load, should be a main checkbox, recomputed by main.js
	public           value: boolean | null;
    public           htmlCheckbox: HTMLInputElement | null;        // element <checkboxId> from document
    public           htmlEditable: {          // only if editable
        htmlCheckboxLabel: HTMLInputElement,  // element <checkboxLabelId> from document
        editButton: HTMLButtonElement;        // element <editEltId> from document
        removeButton: HTMLButtonElement;      // element <removeEltId> from document
    } | null = null;                          // never null after mediaInit IF editable

    constructor(id: string,
                label: string,
                value: boolean | null,                    // null if value is unknown
                editable: boolean) {
        this.id = id;
        this.checkboxId = `${this.id}-checkbox`;
        this.checkboxLabelId = `${this.id}-label`;
        this.editEltId = `${this.id}-editElt`;
        this.removeEltId = `${this.id}-removeElt`;
        this.editable = editable;
        this.label = label;
        this.value = value;
        this.htmlCheckbox = null;  // never null after mediaInit
        this.htmlEditable = null;  // never null after mediaInit IF editable
    }
    mediaInit() {
        this.htmlCheckbox = document.getElementById(this.checkboxId) as HTMLInputElement;
        if (this.editable) {
            this.htmlEditable = {
                htmlCheckboxLabel: document.getElementById(this.checkboxLabelId) as HTMLInputElement,
                editButton: document.getElementById(this.editEltId) as HTMLButtonElement,
                removeButton: document.getElementById(this.removeEltId) as HTMLButtonElement,
            };
        }
    }
    mediaAddEventListener(method: any) {
        this.htmlCheckbox!.addEventListener('input', (event: any) => { method(event); });
    }
    mediaAddEventListenerEdit(method: any) {
        this.htmlEditable!.editButton!.addEventListener('click', () => {
            console.log("media.editButton input");
            const editLabel = '\u{1F527}';   // "&#128295;"
            const validLabel = '\u{2714}';   // "&#10004;"
            let valid = false;
            if (this.htmlEditable!.editButton!.textContent === editLabel) {
                this.htmlEditable!.editButton!.textContent = validLabel;
                valid = false;
            }
            else {
                this.htmlEditable!.editButton!.textContent = editLabel;
                valid = true;
            }
            method(this, valid);
        });
    }
    mediaAddEventListenerRemove(method: any) {
        this.htmlEditable!.removeButton!.addEventListener('click', () => {
            console.log("media.removeButton input");
            method(this);
        });
    }
    mediaUpdateMessage(message: Message) {
        message[this.id] = this.htmlCheckbox!.checked;
        message[this.checkboxLabelId] = this.label;
        console.log(this.id, `mediaUpdateMessage message[${this.id}]`, message[this.id], `message[${this.checkboxLabelId}]`, message[this.checkboxLabelId]);
    }
    mediaEditStart() {
        const ie = document.getElementById(`${this.checkboxLabelId}`) as HTMLInputElement;
        ie.removeAttribute("disabled");
    }
    mediaEditValid(managerId: string) {
        const ie = document.getElementById(`${this.checkboxLabelId}`) as HTMLInputElement;
        ie.setAttribute("disabled", "none");

        // Save
        this.label = this.htmlEditable!.htmlCheckboxLabel!.value!;
        console.log("mediaEditValid", "this.label", this.label);

        // Send mod message
        const message: Message = {
            manager: managerId,
            command: 'mod',
            eltId: this.id,
        };
        this.mediaUpdateMessage(message);
        console.log("mediaEditValid mediaSendMessage", message);
        mediaSendMessage!(message);
    }

    getHtmls(): string[] {
        const classDecl = this.htmlClasses !== '' ? `class="${this.htmlClasses}"` : '';
        const state = this.value ? "checked" : "";
        const labelHtml = this.editable ?
            `<input for="${this.checkboxId}" id="${this.checkboxLabelId}" type="text" value="${this.label}" class="input-as-label" disabled/>` : 
            `<label for="${this.checkboxId}" id="${this.checkboxLabelId}">${this.label}</label>`;

        const html = `<div class="container">
                      <input type="checkbox" ${state} id="${this.checkboxId}" ${classDecl} />
                      ${labelHtml}
                      </div>`;
        // TODO click on input this.checkboxLabelId does NOT change this.checkboxId (as it does for a label)
        const htmls = [html];
        if (this.editable) {
            // edit button
            htmls.push(
            // `<button id="${this.editEltId}">&#9997;</button>`,
            // `<button id="${this.editEltId}">&#9998;</button>`,
            // `<button id="${this.editEltId}">&#128275;</button>`,
            `<button id="${this.editEltId}">&#128295;</button>`,
            // `<button id="${this.editEltId}">&#128393;</button>`,
            // // `<button id="${this.editEltId}">&#128394;</button>`,
            // // `<button id="${this.editEltId}">&#128395;</button>`,
            // // `<button id="${this.editEltId}">&#128396;</button>`,
            // `<button id="${this.editEltId}">&#128397;</button>`,

            // // Valid
            // // `<button id="${this.editEltId}">&#10003;</button>`,
            // `<button id="${this.editEltId}">&#10004;</button>`,
            // // `<button id="${this.editEltId}">&#9745;</button>`,
            // // `<button id="${this.editEltId}">&#9166;</button>`,
            // // `<button id="${this.editEltId}">&#9989;</button>`,

            );
            // remove button
            htmls.push( `<button id="${this.removeEltId}">&#10134;</button>`);
        }
        return htmls;
    }
}

class MediaCheckboxManager {
    public  readonly id: string;
    public  readonly addEltId: string;
	private readonly mainElt: MediaCheckbox;  // All checkbox permits to select/unselect all elts
	public  readonly elts: MediaCheckbox[];
    private readonly autonomous: boolean;
    public  readonly htmlTable: boolean;
    private          eventListenerMethod: any;  // null until mediaAddEventListener, still null if autonomous
    public           editable: {              // only if editable
        addElt: MediaCheckboxAdd;
    } | null = null;

	constructor(id: string,
                mainEltLabel: string,
                editable: boolean = false,
                autonomous: boolean = false) {
        this.id = id;
        this.addEltId = `${this.id}-addElt`;
        this.elts = [];
        this.autonomous = autonomous;
        this.htmlTable = editable;
        {
            // Elts are builded/added dynamically
            //  from div generated by src 
            const srcGroup = document.getElementById(this.id) as HTMLElement;

            // Create a table or a div and replace the srcGroup
            const newGroup: HTMLElement = document.createElement('div');
            newGroup.id = this.id;
            newGroup.innerHTML = this.mediaGetHtml();
            srcGroup.parentNode!.replaceChild(newGroup, srcGroup);

            // Add the All checkbox
            this.mainElt = this.mediaAddNewChildNoMessage(id, "Main", mainEltLabel, false, false);

            // Add all elements as specified into srcGroup
            const descendants = srcGroup.getElementsByTagName("*");
            for (const idx in descendants) {
                const htmlElt = descendants[idx] as HTMLElement;
                if (! (htmlElt instanceof HTMLElement)) {
                    console.log(this.id, `MediaCheckboxManager htmlElt`, htmlElt, "ignored");
                    continue;
                }
                const id = htmlElt.getAttribute("id")!;
                const label = htmlElt.getAttribute("label")!;
                const value = htmlElt.getAttribute("value")! === "true";
                const editable = htmlElt.getAttribute("editable")! === "true";
                console.log(this.id, `MediaCheckboxManager Elt ${label} ${value} ${editable}`, htmlElt);

                this.mediaAddNewChildNoMessage(id, "Elt",  label, value, editable);
            }
            if (editable) {
                this.editable = {
                    addElt: new MediaCheckboxAdd(this, this.addEltId)
                };
                this.mediaAddNewChildHtml(this.addEltId, this.editable.addElt.getHtmls());
                this.editable.addElt.mediaInit();
                this.editable.addElt.mediaAddEventListener();
            }
        }
        this.mediaComputeMainCheckbox();
        this.eventListenerMethod = null;
    }
    mediaGetHtml(): string {
        let html = "";
        if (this.htmlTable) {
            html += `<table>`;
            html += `<tbody>`;
            html += `</tbody>`;
            html += `</table>`;
        }
        return html;
    }
    mediaRemoveChild(elt: MediaCheckbox) {
        console.log(this.id, "mediaRemoveChild", elt);

        // Send remove message
        const message: Message = {
            manager: `${this.id}`,
            command: 'remove',
        };
        message[elt.id] = true;
        console.log(this.id, "mediaRemoveChild mediaSendMessage", message);
        mediaSendMessage!(message);

        // Remove html
        const eltHtml = document.getElementById( `${elt.id}-elt`)!;
        eltHtml.parentNode!.removeChild(eltHtml);
        
        // Remove elt from this
        const index = this.elts.indexOf(elt, 0);
        console.log(this.id, "mediaRemoveChild index", index);
        this.elts.splice(index, 1);

        this.mediaComputeMainCheckbox();
        this.editable!.addElt.mediaUpdateBehavior();
    }
    mediaAddNewChild(label: string, value: boolean): MediaCheckbox {
        const eltId = this.mediaGenerateNewChildId();
        console.log(this.id, "mediaAddNewChild", eltId);
        const elt = this.mediaAddNewChildNoMessage(eltId, "Elt", label, value, true);

        this.mediaComputeMainCheckbox();
        this.editable!.addElt.mediaUpdateBehavior();

        // Send add message
        const message: Message = {
            manager: `${this.id}`,
            command: 'add',
            eltIdToAdd: eltId,
        };
        elt.mediaUpdateMessage(message);
        console.log(this.id, "mediaAddNewChild mediaSendMessage", message);
        mediaSendMessage!(message);

        return elt;
    }
    private mediaGenerateNewChildId(): string {
        let max = -1;
        for (const elt of this.elts) {
            const subIdStr = elt.id.split('-')[1];
            const subId: number = +subIdStr;
            max = Math.max(max, subId);
        }
        return `${this.id}-${max+1}`;
    }
    private mediaAddNewChildNoMessage(eltId: string, kind: string, label: string, value: boolean, editable: boolean): MediaCheckbox {
        console.log(this.id, "mediaAddNewChildNoMessage", eltId);
        const elt = new MediaCheckbox(eltId, label, value, editable);
        if (kind === "Elt") {
            elt.htmlClasses = "subCheckbox";
        }
        const eltHtmls = elt.getHtmls();
        console.log(this.id, "mediaAddNewChildNoMessage", eltId, eltHtmls);

        // Add html into document
        this.mediaAddNewChildHtml(kind === "Elt" ? `${eltId}-elt` : `${eltId}-mainElt`, eltHtmls);

        // Init new element from html
        elt.mediaInit();
        if (kind === "Elt") {
            this.elts.push(elt);
        }

        // Add listener
        this.mediaEltAddEventListener(elt);

        return elt;
    }
    private mediaAddNewChildHtml(eltId: string, eltHtmls: string[]) {
        console.log(this.id, "mediaAddNewChildHtml", eltId, eltHtmls);

        // Add html into document
        const newRow: HTMLElement = document.createElement(this.htmlTable ? 'tr' : 'div');
        newRow.id = eltId;
        newRow.innerHTML = this.getHtmlEltRaw(eltId, eltHtmls);

        let parent = document.getElementById(this.id)!;
        if (this.htmlTable) {
            parent = parent.getElementsByTagName('tbody')[0];
        }

        if (parent.hasChildNodes() === false) {
            // 1st child, should be main checkbox
            parent.insertBefore(newRow, null);
        }
        else {
            // not 1st child, should be elt checkbox or add checkbox
            const rowBeforeId = this.elts.length > 0 ? `${this.elts.at(-1)!.id}-elt` : `${this.mainElt.id}-mainElt`;
            const rowBefore = document.getElementById(rowBeforeId)!;
            console.log(`rowBeforeId=${rowBeforeId} rowBefore=${rowBefore}`);
            rowBefore.parentNode!.insertBefore(newRow, rowBefore.nextSibling);
        }
    }
    mediaEltAddEventListener(elt: MediaCheckbox) {
        elt.mediaAddEventListener((event: any) => { this.mediaEventListenerInnerMethod(event); });
        if (elt.editable) {
            elt.mediaAddEventListenerEdit((_elt: MediaCheckbox, valid: boolean) => {
                console.log(this.id, "mediaAddEventListenerEdit", elt.id, valid ? "valid" : "edit");
                if (valid) {
                    elt.mediaEditValid(this.id);
                    this.editable!.addElt.mediaUpdateBehavior();
                }
                else {
                    elt.mediaEditStart();
                }
            });
           elt.mediaAddEventListenerRemove((_elt: MediaCheckbox) => {
                this.mediaRemoveChild(elt);
            });
        }
    }
    mediaAddEventListener(method: any) {
        this.eventListenerMethod = method;

        for (const elt of this.elts) {
            this.mediaEltAddEventListener(elt);
        }
        if (this.mainElt) {
            this.mainElt.mediaAddEventListener((event: any) => { this.mediaEventListenerInnerMethod(event); });
        }
    }
    private mediaEventListenerInnerMethod(event: any) {
        this.mediaManage(event);

        if (this.eventListenerMethod) {
            console.log(this.id, "mediaAddEventListenerInner callback call method");
            this.eventListenerMethod(event);
        }
        else {
            console.log(this.id, "mediaAddEventListenerInner callback call mediaBuildMessage");
            const message = this.mediaBuildMessage();
            console.log(this.id, "mediaAddEventListenerInner callback call mediaSendMessage");
            mediaSendMessage!(message);
        }
    }
    mediaUpdateMessage(message: Message) {
        if (this.autonomous) {
            console.error(this.id, "mediaUpdateMessage must not be called if autonomous");
        }

        for (const elt of this.elts) {
            elt.mediaUpdateMessage(message);
        }
    }
    private mediaBuildMessage(): {} {
        if (!this.autonomous) {
            console.error(this.id, "mediaBuildMessage must not be called if not autonomous");
        }

        const message = {
            manager: `${this.id}`,
            command: 'exec',
        };

        for (const elt of this.elts) {
            elt.mediaUpdateMessage(message);
        }
        return message;
    }

    private mediaManage(event: any) {
        if (this.mainElt.htmlCheckbox === event.target) {
            // Change all subCheckboxes
            for (const elt of this.elts) {
                if (elt.htmlCheckbox) {
                    elt.htmlCheckbox.checked = event.target?.checked;
                }
            }
            return;
        }

        for (const elt of this.elts) {
            if (elt.htmlCheckbox === event.target) {
                this.mediaComputeMainCheckbox();
                return;
            }
        }

        // Impossible
    }

    private mediaComputeMainCheckbox() {
        if (this.mainElt && this.mainElt.htmlCheckbox) {
            const allChecked = this.elts.length !== 0 && [...this.elts].every(elt => elt.htmlCheckbox!.checked);
            this.mainElt.htmlCheckbox.checked = allChecked;
        }
    }

    private getHtmlEltRaw(_eltId: string, eltHtmls: string[]): string {
        let html = "";
        if (this.htmlTable) {
            for (const eltHtml of eltHtmls) {
                html += `<td>${eltHtml}</td>`;
            }
        }
        else {
            for (const eltHtml of eltHtmls) {
                html += `<div>${eltHtml}</div>`;
            }
        }
        return html;
    }
}

export class MediaCaseManager extends MediaCheckboxManager {
	constructor() {
        super("case", 'All');
    }
}

export class MediaWordManager extends MediaCheckboxManager {
    constructor() {
        super("word", 'Whole word');
    }
}

export class MediaCheckboxAdd {
    private readonly manager: MediaCheckboxManager;
	private readonly id: string;                             // id inside message and load/save into context
    private readonly htmlLabelId: string;
    private readonly htmlApplyId: string;
    private          media: {
        label: HTMLInputElement,
        button: HTMLButtonElement;
    } | null = null;                  // never null after mediaInit

    constructor(manager: MediaCheckboxManager, id: string) {
        this.manager = manager;
        this.id = id;
        this.htmlLabelId  = `${this.id}-label`;
        this.htmlApplyId = `${this.id}-apply`;
    }

    mediaInit() {
        this.media = {
            label:  document.getElementById(this.htmlLabelId ) as HTMLInputElement,
            button: document.getElementById(this.htmlApplyId)  as HTMLButtonElement,
        };
        this.mediaUpdateBehavior();
    }
    mediaUpdateBehavior() {
        // Forbid empty label
        if (this.media!.label.value === '') {
            this.media!.label.classList.remove('error');
            this.media!.button.disabled = true;
            return;
        }

        // Forbid doubles
        for (const elt of this.manager.elts) {
            if (this.media!.label.value === elt.label) {
                this.media!.label.classList.add('error');
                this.media!.button.disabled = true;
                return;
            }
        }

        this.media!.label.classList.remove('error');
        this.media!.button.disabled = false;
    }
    mediaAddEventListener() {
        this.media!.label.addEventListener('input', () => {
            console.log(this.id, `mediaAddEventListener label input = ${this.media!.label.value}`);
            this.mediaUpdateBehavior();
        });
        this.media!.button.addEventListener('click', () => {
            console.log(this.id, "mediaAddEventListener button click");
            this.manager.mediaAddNewChild(this.media!.label.value, false);
        });
    }

    getHtmls(): string[] {
        const htmls = [];
        htmls.push(`<input  id="${this.htmlLabelId }" type="text" placeholder="*.cpp,*.c,*.h">`);
        htmls.push(``);  // no edit/valid button
        htmls.push(`<button id="${this.htmlApplyId}">&#10133;</button>`);
        return htmls;
    }
}

export class MediaFilesToIncludeManager extends MediaCheckboxManager {
    constructor() {
        super("filesToInclude", "All", true, true);
    }
}

export class MediaFilesToExcludeManager extends MediaCheckboxManager {
    constructor() {
        super("filesToExclude", "All", true, true);
    }
}

// Defines some parts of the mmi
export class MediaMmi {
    public readonly caseManager: MediaCaseManager;
    public readonly wordManager: MediaWordManager;
    public readonly filesToIncludeManager: MediaFilesToIncludeManager;
    public readonly filesToExcludeManager: MediaFilesToExcludeManager;
    public readonly managers: MediaCheckboxManager[];
    private readonly mainManagers: MediaCheckboxManager[];
    private readonly otherManagers: MediaCheckboxManager[];

	constructor(mediaSendMsg: any) {
        this.caseManager           = new MediaCaseManager();
        this.wordManager           = new MediaWordManager();
        this.filesToIncludeManager = new MediaFilesToIncludeManager();
        this.filesToExcludeManager = new MediaFilesToExcludeManager();
        this.mainManagers  = [this.caseManager, this.wordManager];
        this.otherManagers = [this.filesToIncludeManager, this.filesToExcludeManager];
        this.managers      = this.mainManagers.concat(this.otherManagers);
        mediaSendMessage = mediaSendMsg;
    }

    mediaAddEventListener(method: any) {
        for (const manager of this.mainManagers) {
            manager.mediaAddEventListener(method);
        }
        for (const manager of this.otherManagers) {
            manager.mediaAddEventListener(null);
        }
    }
    mediaUpdateMainMessage(message: Message) {
        for (const manager of this.mainManagers) {
            manager.mediaUpdateMessage(message);
        }
    }
}
